name: Publish Packages

on:
  workflow_run:
    workflows: ["Build and Test"]
    branches: [ main ]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Install dependencies
      run: dotnet restore
    - name: Pack
      run: dotnet pack -c Release --no-restore -o .

    - name: Publish Nuget packages
      run: dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json --skip-duplicate -n -k ${{secrets.NUGET_API_KEY}}
    - name: Tag release
      # Extract the version from the common.props' Version tag.
      run: |
        version=$(cat common.props | grep -Eo '<Version>(.*)</Version>' | sed -r 's|<Version>(.*)</Version>|\1|')
        tagName=v$version
        echo "Tagging version $version as '$tagName'"
        git tag $tagName
        git push origin $tagName
        echo 'Successfully tagged.'
