name: Pull Request - Build and Test

on:
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:'XPlat Code Coverage' --results-directory ./coverage/temp

    - name: Generate lcov
      uses: danielpalme/ReportGenerator-GitHub-Action@5.0.4
      with:
        reports: coverage/temp/**/coverage.cobertura.xml
        targetdir: coverage/report/
        reporttypes: lcov
        assemblyfilters: -*UnitTests*

    - name: Upload to Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage/report/lcov.info
        flag-name: Unit
